#!/bin/sh
set -eu

if ! git diff --quiet --staged; then
	echo "You have staged changes; cannot ensure docs are up-to-date."
	exit 1
fi

./scripts/g.sh

if git diff --quiet -- bin/g; then
	exit 0
fi

git add bin/g
name="github-actions[bot]"
email="41898282+github-actions[bot]@users.noreply.github.com"
GIT_COMMITTER_NAME="$name" GIT_COMMITTER_EMAIL="$email" git commit --no-verify -m \
"Update bin/g docs

via .githooks/pre-push"
