#!/bin/sh
set -eu

execute_if_modified() {
	command="$1"
	shift # Remove the first argument, which is the command, to leave the patterns.
	patterns="$*"

	untracked_changes=$(git ls-files --others --exclude-standard)
	# shellcheck disable=2086 # Expanding patterns is the desired behavior here
	unstaged_changes=$(git diff --name-only -- $patterns)
	# shellcheck disable=2086
	staged_changes=$(git diff --staged --name-only -- $patterns)

	if [ -n "$untracked_changes" ] || [ -n "$unstaged_changes" ] || [ -n "$staged_changes" ]; then
		echo "Changes detected in $patterns. Executing $command..."
		eval "$command"
	fi
}

# Not executing everything always is what keeps this script fast.
echo "--no-verify can be used to skip git hooks."
execute_if_modified 'make shellcheck' '*.sh' './.githooks/*' './bin/*'

if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
	echo "You have unstaged changes; commit contents might not pass 'make ci'."
	exit 1
fi

# Known issues:
# * Doesn't handle files with a space in the name well
# * Doesn't consistently detect a tracked file having an unstaged change.
# * Having to configure what shellcheck scans for in two places is bit of a pain. One source of truth please.
