#!/bin/sh
set -eu

execute_if_modified() {
	command="$1"
	shift # Remove the first argument, which is the command, to leave the patterns.
	patterns="$*"

	# shellcheck disable=2086 # Expanding patterns is the desired behavior here
	unstaged_changes=$(git diff -z --name-only -- $patterns)
	# shellcheck disable=2086
	staged_changes=$(git diff -z --name-only --staged -- $patterns)

	if [ -n "$unstaged_changes" ] || [ -n "$staged_changes" ]; then
		echo "Changes detected in $patterns. Executing $command..."
		eval "$command"
	fi
}

# Not executing everything always is what keeps this script fast.
echo "--no-verify can be used to skip git hooks."
execute_if_modified 'make shellcheck' '*.sh' './.githooks/*' './bin/*'

prefix="You have"
postfix="changes; commit contents might not pass 'make ci'."

if ! git diff --quiet; then
	echo "$prefix unstaged $postfix"
	exit 1
fi

if [ -n "$(git ls-files --others --exclude-standard)" ]; then
	echo "$prefix untracked $postfix"
	exit 1
fi

# Improvement idea: only one source of truth for granularity. Currently there's three:
#  1. this file
#  2. .github/workflows/shellcheck.yml <- this one we can't get rid of, i.e., it must be used as the source of truth?
#  3. scripts/shellcheck.sh
