#!/bin/sh
set -eu

# G utils
# Script to generate the 'g' script for displaying the available Git utils.

{
	shebang="#!/bin/sh"

	echo "$shebang"
	echo "set -eu"
	echo
	echo "# DO NOT EDIT MANUALLY! THIS SCRIPT IS GENERATED BY g.sh"
	echo
	printf "echo \""
	init=false
	for path in bin/g*; do
		[ "$path" = "bin/g" ] && continue
		[ "$init" = "true" ] && printf "\n"
		file=$(basename "$path")

		printf %s "$file"

		init=true
	done
	echo "\""
} > bin/g
