name: Validate
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: anttiharju/actions/check-shellcheck@v0

      - if: always()
        name: Prettier
        uses: anttiharju/actions/check-prettier@v0

      - if: always()
        name: EditorConfig
        uses: anttiharju/actions/check-editorconfig@v0
